# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AlamofireJSONweather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 4.0.0'
  # Pods for AlamofireJSONweather

end
