# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'AlamofireTest1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlamofireTest1
pod 'Alamofire', '~> 5.0.0-rc.3'
end
